# Generated by Django 5.0.3 on 2024-03-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрики',
                'verbose_name_plural': 'Рубрика',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bboard',
            options={'ordering': ['-published'], 'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявление'},
        ),
        migrations.AlterField(
            model_name='bboard',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bboard',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
