# Generated by Django 5.0.3 on 2024-03-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_borrowed_to_who_alter_borrowed_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='what',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.belonging', verbose_name='Принадлежит'),
        ),
    ]
