# Generated by Django 5.1.4 on 2024-12-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
