# Generated by Django 5.1.4 on 2024-12-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
