# Generated by Django 5.0.7 on 2024-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bb_options_bb_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('s', 'Продам '), ('b', 'Куплю'), ('c', 'Обменяю')], default='s', max_length=1),
        ),
    ]
