# Generated by Django 5.0.7 on 2024-07-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('Купля-продажа', [('s', 'Продам '), ('b', 'Куплю')]), ('Обмен', [('c', 'Обменяю')])], default='s', max_length=1, verbose_name='Вид объявлений'),
        ),
    ]
