# Generated by Django 5.0.7 on 2024-07-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.measure', verbose_name='Меры измерения'),
        ),
    ]
