# Generated by Django 5.0.7 on 2024-07-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bb_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Мера', 'verbose_name_plural': 'Меры измерения'},
        ),
    ]
