# Generated by Django 5.0.7 on 2024-07-25 08:04

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_measure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=models.SET(bboard.models.Bb.get_first_rubric), to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
