# Generated by Django 5.0.7 on 2024-07-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_spare_advuser_bb_spare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
